apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

# Flux envsubst replaces variables found in `deploy-vars.env` or falls back to defaults
#
namespace: ${DEPLOY_NAMESPACE:=qcon-web}

commonLabels:
  environment: review

# Prefix/Suffix required for VaultAuth configuration
#
namePrefix: qcon-web-
nameSuffix: -review

# Teach kustomize how to update generated names
#
configurations:
  - kustomizeconfig.yaml

commonAnnotations:
  version: ${GIT_TAG:=stable}

images:
  - name: qcon-web
    newName: ${IMAGE_NAME:=registry.ltc.bcit.ca/web-apps/qcon/qcon-web}
    newTag: ${IMAGE_TAG:=stable}

# Patches ingress with "review--"
#
patches:
  - target:
      kind: Ingress
    path: ingress-patch.yaml

  # Incorporate vault-secrets
  #
  # adds `-review` suffix to VaultAuth `spec.mount`
  - target:
      kind: VaultAuth
    path: vault-secrets-review/vault-auth-patch.yaml

components:
  # Include environment-specific secrets
  - ./vault-secrets-review
  # Required for VaultAuth role and serviceaccounts
  - ../../base/components/vault-auth
