apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ./nginx-unprivileged
  - ingress.yaml
  - serviceaccount.yaml

# Teach kustomize how to update generated names
#
configurations:
  - kustomizeconfig.yaml

commonLabels:
  app: qcon-web
  app.kubernetes.io/name: qcon-web

# Enables Kustomize to simplify the deployment name
#
patches:
  - target:
      kind: Deployment
      labelSelector: "app=nginx"
    path: deployment.yaml
    options:
      allowNameChange: true

configMapGenerator:
  # Configure postgres to allow all connections
  #
  - name: postgres-config
    literals:
      - POSTGRES_HOST_AUTH_METHOD=trust

# Replaces default nginx config
#
components:
  - ../../conf.d
