# This file is for teaching kustomize how to substitute names
#
---
nameReference:

  - kind: VaultStaticSecret
    fieldSpecs:
      - kind: VaultStaticSecret
        path: spec/destination/name
      - kind: Deployment
        path: spec/template/spec/containers/envFrom/secretRef/name
