apiVersion: apps/v1
kind: Deployment
metadata:
  name: deployment
  labels:
    app: nginx
spec:
  progressDeadlineSeconds: 600
  revisionHistoryLimit: 2
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  replicas: 1
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
        - name: nginx
          image: nginxinc/nginx-unprivileged:1.25-alpine
          ports:
            - containerPort: 8080
              protocol: TCP
          securityContext:
            capabilities:
              drop:
                - NET_RAW
            runAsNonRoot: true
            allowPrivilegeEscalation: false
            readOnlyRootFilesystem: true
            runAsUser: 999
          volumeMounts:
            - mountPath: /tmp
              name: tmp
            - name: nginx-config
              mountPath: /etc/nginx/conf.d
          resources:
            limits:
              cpu: "100m"
              memory: "250Mi"
            requests:
              cpu: "100m"
              memory: "100Mi"
      volumes:
        - name: nginx-config
          configMap:
            name: nginx-config
        - emptyDir: {}
          name: tmp
