# This file is for teaching kustomize how to substitute names
#
---
nameReference:

- kind: ServiceAccount
  fieldSpecs:
    - kind: VaultAuth
      path: spec/kubernetes/serviceAccount

- kind: VaultAuth
  fieldSpecs:
    - kind: VaultAuth
      path: spec/kubernetes/role
    - kind: VaultStaticSecret
      path: spec/vaultAuthRef